-- GOOD LUCK SOCIETY - SUPABASE POSTGRESQL SCHEMA & ATOMIC RPC FUNCTIONS

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT DEFAULT 'user',
  phone TEXT,
  address TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 2. CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT
);

-- 3. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC(10,2) NOT NULL,
  discount_price NUMERIC(10,2) DEFAULT 0,
  rating NUMERIC(3,2) DEFAULT 5.0,
  reviews_count INT DEFAULT 0,
  quote_front TEXT,
  quote_back TEXT,
  tag TEXT,
  badge TEXT,
  image_front TEXT NOT NULL,
  image_back TEXT NOT NULL,
  images JSONB DEFAULT '[]'::jsonb,
  color TEXT,
  material TEXT,
  fit TEXT,
  sizes JSONB DEFAULT '[]'::jsonb,
  stock INT DEFAULT 50,
  in_stock BOOLEAN DEFAULT TRUE,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  description TEXT,
  details JSONB DEFAULT '[]'::jsonb,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 4. ORDERS TABLE
CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  shipping_address TEXT NOT NULL,
  subtotal NUMERIC(10,2) NOT NULL,
  discount_amount NUMERIC(10,2) DEFAULT 0,
  shipping_fee NUMERIC(10,2) DEFAULT 0,
  final_amount NUMERIC(10,2) NOT NULL,
  status TEXT DEFAULT 'pending',
  payment_status TEXT DEFAULT 'pending',
  cashfree_order_id TEXT,
  cashfree_payment_id TEXT,
  carrier_name TEXT,
  tracking_number TEXT,
  shipped_at TIMESTAMPTZ,
  estimated_delivery TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 5. ORDER_ITEMS TABLE
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  product_name TEXT NOT NULL,
  price NUMERIC(10,2) NOT NULL,
  quantity INT NOT NULL,
  size TEXT NOT NULL
);

-- 6. PAYMENTS TABLE
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  cashfree_order_id TEXT NOT NULL,
  cashfree_payment_id TEXT,
  cashfree_signature TEXT,
  amount NUMERIC(10,2) NOT NULL,
  currency TEXT DEFAULT 'INR',
  status TEXT DEFAULT 'created',
  raw_response JSONB,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 7. CART_ITEMS TABLE
CREATE TABLE IF NOT EXISTS cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  size TEXT NOT NULL,
  quantity INT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 8. USER_ADDRESSES TABLE
CREATE TABLE IF NOT EXISTS user_addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  customer_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  address_line TEXT NOT NULL,
  city TEXT,
  state TEXT,
  pincode TEXT,
  is_default BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 9. COUPONS TABLE
CREATE TABLE IF NOT EXISTS coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  discount_type TEXT DEFAULT 'percentage',
  discount_value NUMERIC(10,2) NOT NULL,
  min_order_amount NUMERIC(10,2) DEFAULT 0,
  max_discount NUMERIC(10,2),
  usage_limit INT,
  used_count INT DEFAULT 0,
  expires_at TIMESTAMPTZ,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 10. AUDIT_LOGS TABLE
CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT,
  admin_email TEXT,
  action TEXT NOT NULL,
  entity_type TEXT,
  entity_id TEXT,
  details TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 11. WISHLIST TABLE
CREATE TABLE IF NOT EXISTS wishlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, product_id)
);

-- ENSURE EXISTING IDENTITY COLUMNS ALLOW EXPLICIT ID INSERTS FOR MIGRATION
ALTER TABLE users ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE categories ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE order_items ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE payments ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE cart_items ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE user_addresses ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE coupons ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE audit_logs ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE wishlist ALTER COLUMN id SET GENERATED BY DEFAULT;

-- PRODUCTION PERFORMANCE & IDEMPOTENCY INDEXES
CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_cashfree_order_id ON orders (cashfree_order_id) WHERE cashfree_order_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_cashfree_payment_id ON orders (cashfree_payment_id) WHERE cashfree_payment_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_cashfree_payment_id ON payments (cashfree_payment_id) WHERE cashfree_payment_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_payments_cashfree_order_id ON payments (cashfree_order_id);
CREATE INDEX IF NOT EXISTS idx_payments_order_id ON payments (order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON order_items (product_id);

-- PRODUCTION-SAFE ATOMIC TRANSACTION & WEBHOOK IDEMPOTENCY RPC FUNCTION
CREATE OR REPLACE FUNCTION fulfill_order_payment_atomic(
  p_order_id TEXT,
  p_cashfree_order_id TEXT,
  p_cashfree_payment_id TEXT,
  p_cashfree_signature TEXT
) RETURNS JSONB AS $$
DECLARE
  v_current_payment_status TEXT;
  item RECORD;
BEGIN
  -- 1. Row Lock: Acquire row lock on target order to prevent concurrent execution races
  SELECT payment_status
  INTO v_current_payment_status
  FROM orders
  WHERE id = p_order_id
  FOR UPDATE;

  -- Exit if order record does not exist
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'already_processed', false, 'message', 'Order not found');
  END IF;

  -- 2. Idempotency Check A: If order is already paid, do not re-process or re-deduct stock
  IF v_current_payment_status = 'paid' THEN
    RETURN jsonb_build_object(
      'success', true, 
      'already_processed', true, 
      'message', 'Order is already marked as paid. Stock deduction skipped.'
    );
  END IF;

  -- 3. Idempotency Check B: If this exact cashfree_payment_id was already captured in payments table
  IF p_cashfree_payment_id IS NOT NULL AND EXISTS (
    SELECT 1 FROM payments 
    WHERE cashfree_payment_id = p_cashfree_payment_id AND status = 'captured'
  ) THEN
    UPDATE orders 
    SET payment_status = 'paid', 
        status = 'processing', 
        cashfree_payment_id = p_cashfree_payment_id
    WHERE id = p_order_id;

    RETURN jsonb_build_object(
      'success', true, 
      'already_processed', true, 
      'message', 'Cashfree payment ID already captured. Stock deduction skipped.'
    );
  END IF;

  -- 4. Update order payment status to paid
  UPDATE orders 
  SET payment_status = 'paid',
      status = 'processing',
      cashfree_order_id = COALESCE(p_cashfree_order_id, cashfree_order_id),
      cashfree_payment_id = COALESCE(p_cashfree_payment_id, cashfree_payment_id)
  WHERE id = p_order_id;

  -- 5. Upsert Payment Record (Update existing draft payment or insert captured record)
  IF EXISTS (SELECT 1 FROM payments WHERE order_id = p_order_id OR (p_cashfree_order_id IS NOT NULL AND cashfree_order_id = p_cashfree_order_id)) THEN
    UPDATE payments
    SET status = 'captured',
        cashfree_payment_id = COALESCE(p_cashfree_payment_id, cashfree_payment_id),
        cashfree_signature = COALESCE(p_cashfree_signature, cashfree_signature)
    WHERE order_id = p_order_id OR (p_cashfree_order_id IS NOT NULL AND cashfree_order_id = p_cashfree_order_id);
  ELSE
    INSERT INTO payments (order_id, cashfree_order_id, cashfree_payment_id, cashfree_signature, amount, status)
    SELECT id, COALESCE(p_cashfree_order_id, cashfree_order_id, 'N/A'), p_cashfree_payment_id, p_cashfree_signature, final_amount, 'captured'
    FROM orders WHERE id = p_order_id;
  END IF;

  -- 6. Atomic Stock Deduction (Executes exactly ONCE per unique order payment)
  FOR item IN SELECT product_id, quantity FROM order_items WHERE order_id = p_order_id LOOP
    UPDATE products 
    SET stock = GREATEST(0, stock - item.quantity),
        in_stock = (GREATEST(0, stock - item.quantity) > 0)
    WHERE id = item.product_id;
  END LOOP;

  RETURN jsonb_build_object(
    'success', true,
    'already_processed', false,
    'message', 'Order payment fulfilled and stock updated atomically.'
  );
END;
$$ LANGUAGE plpgsql;

-- PRODUCTION-SAFE SEQUENCE RESET RPC FUNCTION
CREATE OR REPLACE FUNCTION reset_identity_sequences() RETURNS JSONB AS $$
BEGIN
  PERFORM setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1));
  PERFORM setval(pg_get_serial_sequence('categories', 'id'), COALESCE((SELECT MAX(id) FROM categories), 1));
  PERFORM setval(pg_get_serial_sequence('order_items', 'id'), COALESCE((SELECT MAX(id) FROM order_items), 1));
  PERFORM setval(pg_get_serial_sequence('payments', 'id'), COALESCE((SELECT MAX(id) FROM payments), 1));
  PERFORM setval(pg_get_serial_sequence('cart_items', 'id'), COALESCE((SELECT MAX(id) FROM cart_items), 1));
  PERFORM setval(pg_get_serial_sequence('user_addresses', 'id'), COALESCE((SELECT MAX(id) FROM user_addresses), 1));
  PERFORM setval(pg_get_serial_sequence('coupons', 'id'), COALESCE((SELECT MAX(id) FROM coupons), 1));
  PERFORM setval(pg_get_serial_sequence('audit_logs', 'id'), COALESCE((SELECT MAX(id) FROM audit_logs), 1));
  PERFORM setval(pg_get_serial_sequence('wishlist', 'id'), COALESCE((SELECT MAX(id) FROM wishlist), 1));
  
  RETURN jsonb_build_object('success', true, 'message', 'All identity sequences reset to max(id) successfully.');
END;
$$ LANGUAGE plpgsql;
